---
- name: Install node and npm 
  hosts: 159.65.24.16
  tasks: 
    - name: Update apt repo and cache 
      apt: update_cache=yes force_apt_get=yes cache_valid_time=360
    - name: Install nodejs and npm 
      apt: 
        pkg:
          - nodejs
          - npm 

- name: Create new linux user for node app 
  hosts: 159.65.24.16
  tasks: 
    - name: Create linux user
      user:
        name: george
        comment: george admin
        group: admin 
      register: user_creation_result
    - debug: msg={{user_creation_result}}    


- name: Deploy nodejs app
  hosts: 159.65.24.16
  become: True
  become_user: george 
  tasks: 
    - name: Unpack the nodejs file 
      unarchive: 
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}" 
      register: user_creation_result
    - debug: msg={{user_creation_result.uid}}   
    - name: Install dependencies
      npm: 
        path: "{{destination}}/package"
    - name: Start the application
      command: 
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0   
    - name: Ensure app is running
      shell: ps aux | grep node  
      register: app_status
    - debug: msg={{app_status.stdout_lines}}  