---
- name: Install node and npm 
  hosts: 104.248.31.172
  tasks: 
    - name: Update apt repo and cache 
      apt: update_cache=yes force_apt_get=yes cache_valid_time=360
    - name: Install nodejs and npm 
      apt: 
        pkg:
          - nodejs
          - npm 
- name: Deploy nodejs app
  hosts: 104.248.31.172
  tasks: 
      - name: Unpack the nodejs file 
        unarchive: 
        src: /home/ebeh/projects/ansible/simple-nodejs/nodejs-app-1.0.0.tgz
        dest: /root/ 
        
  