---
- name: Configure nginx web server
  hosts: webserver
  tasks:
  - name: uninstall nginx server
    apt: 
      name: nginx=1.22.0-1ubuntu1
      state: absent
  - name: start nqinx server
    service:
      name: nginx
      state: stopped 